# Generated by Django 4.2.13 on 2024-07-12 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_portfolio_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='created_at',
        ),
    ]
