# Generated by Django 4.2.13 on 2024-07-12 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_portfolio_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='message',
            field=models.TextField(),
        ),
    ]
