# Generated by Django 4.2.13 on 2024-07-16 07:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_portfolio_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='posted_at',
            field=models.DateTimeField(default=datetime.timezone),
        ),
    ]
