# Generated by Django 4.2.13 on 2024-07-16 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_portfolio_posted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='posted_at',
            field=models.DateTimeField(),
        ),
    ]
