# Generated by Django 4.2.13 on 2024-07-16 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_portfolio_posted_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='posted_at',
        ),
    ]
